repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.7
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11
    hooks:
      - id: ruff-check
        args: []       # sรณ checa, sem corrigir
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format