[project]
name = "clean-architecture-na-pratica"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pre-commit>=4.2.0",
    "ruff>=0.11.11",
]

[tool.ruff]
src = ["src", "."]

extend-select = ["E", "W"]
